name: kus
description: Review App For Safety Regulations on Greek stores .

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #Provider Package
  provider: ^5.0.0

  #HTTP
  http: ^0.13.0

  #URL Launcher
  url_launcher: ^6.0.2

  #JSON Serializable
  #json_serializable: ^3.5.0

  #Font Awesome
  font_awesome_flutter: ^8.12.0

  #Geolocator
  #geolocator: ^7.0.1
  #Google Places
  #flutter_google_places: ^0.2.8

  # New Google Firebase Packages
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  #firebase_storage: ^8.0.0
  
  #Animated Text Kit
  animated_text_kit: ^4.0.0

  #Modal Progress Hud
  modal_progress_hud: ^0.1.3

  #Speed Dial
  flutter_speed_dial: ^2.1.1
  
  #Flusbar
  another_flushbar: ^1.10.15

  #Auto Complete TextField
  #Dropdown Field with Autocomplete
  dropdownfield: ^1.0.3

  #Alert Packages
  rflutter_alert: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

#Assets Folder: images and icons
  assets:
    - assets/images/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  #App Fonts
  fonts:
     - family: Nexa
       fonts:
          - asset: fonts/Nexa-Bold.otf
          - asset: fonts/Nexa-Light.otf
     - family: Gotham
       fonts:
          - asset: fonts/GothamGRBold.otf
          - asset: fonts/GothamGRBookRegular.otf
